### ISSUE TITLE
Extending createCustom with custom types

### ISSUE THREAD

**Issue by mattpocock** [themsammy/tailwindcss-classnames#4]
## The Problem

Currently, it's not easy (or possible?) to extend the default tailwind types with other types.

```ts
import { createCustom } from 'tailwindcss-classnames';

createCustom<CustomClasses>();

type CustomClasses = 'bg-smoke-100';
```

Produces an error:

`Type '"bg-smoke-100"' does not satisfy the constraint 'TClasses'.`

## The Solution

There is probably a technical solution to this, but I couldn't find it immediately and wanted advice before I send a PR to the repo.

It also struck me what a pain it would be to have to add custom types: to add a color, you'd have to specify:

```
bg-<color>-100
...etc
text-<color>-100
...etc
placeholder-<color>-100
...etc
```

And other variations I'm not considering.

Would it be useful to have a CLI tool which could target your tailwind config and generate these types?

**Comment by shrugs** [comment]
likewise ran into this - would be cool to extend the TClasses type, not just constrain it.

in the meantime, erasing the type of the custom class name you have will do the trick: `classnames('my-custom-class' as any)`, but naturally it's not super fun to do :D

**Comment by themsammy** [comment]
Adding a CLI tool is a really great idea!

**Comment by fabiokandrade** [comment]
Great idea! 
Something like https://github.com/esamattis/postcss-ts-classnames

**Comment by themsammy** [comment]
The CLI is now available for generating classes with colors and breakpoints.
`tailwindcss-classnames@next`

**Comment by sarodspirit** [comment]
Do you have a sample tsconfig ? Still not getting correct classes unless I import from generated file
