### ISSUE TITLE
types don't account for plain string in classnames() args

### ISSUE THREAD

**Issue by shrugs** [themsammy/tailwindcss-classnames#5]
i'm trying to add `className` to a custom component, passing `className` in as a prop

i'm not super familiar with how the types are structured, but my typescript is complaining if i attempt to pass a plain string into the `classnames` function along with some tailwind properties

```tsx
const avatarStyle = cn('rounded-full', 'border-4', 'border-white');

function Avatar({
  className,
  src,
  name,
}: { name: string, className: string } & Pick<ImgHTMLAttributes<HTMLImageElement>, 'src'>) {
  return (
    <img
      className={cn(className as any, avatarStyle)}
      src={src}
      alt={`${name} profile image`}
    ></img>
  );
}

export default Avatar;
```

in order to make typescript happy, i have to cast it to any (`className as any`) and then it'll compile

thoughts?

**Comment by themsammy** [comment]
Hello @shrugs,
The `classnames` function allows strings of Tailwindcss classes only, so if you want to add custom classes you can do it with a template literal or string concatenation:

`className={avatarStyle + " " + className}`
